### ISSUE TITLE
Remove Python version from Pipfile

### ISSUE THREAD

**Issue by tgandor** [willardb/rocketchat-history-downloader#4]
When having a Python version above 3.5, `pipenv` complains and refuses `pipenv install`.

There is a workaround, i.e.:
```
pipenv install --python 3.7
```
(for example).

This causes extra burden for people not knowing `pipenv` and just following the README.

Unfortunately, there is no possibility of `python_version = ">= 3.5"` as the value.
(there was an issue in `pipenv`, and it was rejected. However, `poetry` depenency manager, which looks like a `pipenv` done right, has this feature. But you may not want to switch to it.)

However, since any Python versions below 3.5 are already dead anyway, I'd suggest to remove this requirement from the Pipfile altogether.

**Comment by willardb** [comment]
Thanks for the info, and thanks for the suggestion w.r.t `poetry` -- I'll look into using it. 

For now, I've removed the explicit Python 3.5 requirement and that seems like a good first step.
